### ISSUE TITLE
`.lego-pane--empty` can be rewritten to use `flex-center` mixin

### ISSUE THREAD

**Issue by danoc** [optimizely/lego#67] opened 2015-07-20 18:57 UTC
This class can be rewritten to extend the mixin below it:

```
.lego-pane--empty {
  @include display(flex);
  @include justify-content(center);
  @include align-items(center);
}
```

```
@mixin flex-center {
  @include display(flex);
  @include justify-content(center);
  @include align-items(center);
}
```

Output:
```
.lego-pane--empty {
  @include flex-center;
}
```

@tomgenoni – Thoughts? I'll make the change.

**Comment by tomgenoni** [comment] 2015-07-20 20:10
That's fine. The layout system/naming could use a pass.

**Comment by tomgenoni** [comment] 2015-09-09 20:27
Essentially a dupe of #116

**Closed by tomgenoni** 2015-09-09 20:27 UTC
Labels: patch
